# Generated by Django 3.1.2 on 2020-12-01 22:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_name', models.CharField(max_length=30)),
                ('assign_description', models.CharField(max_length=250)),
                ('assign_completion', models.BooleanField()),
                ('assign_duedate', models.DateField(blank=True, default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
                ('group_description', models.CharField(max_length=100)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loginpage.classes')),
                ('user', models.ManyToManyField(to='loginpage.UserProfile')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
