# Generated by Django 3.1.2 on 2020-12-02 16:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_main', models.ImageField(upload_to='photos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
                ('group_description', models.CharField(default='IS 402, IS 404', max_length=100)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user2', to=settings.AUTH_USER_MODEL)),
                ('user3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user3', to=settings.AUTH_USER_MODEL)),
                ('user4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user4', to=settings.AUTH_USER_MODEL)),
                ('user5', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user5', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_name', models.CharField(max_length=30)),
                ('assign_description', models.CharField(max_length=250)),
                ('assign_completion', models.BooleanField()),
                ('assign_duedate', models.DateField(blank=True, default=datetime.datetime.today)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loginpage.group')),
            ],
            options={
                'db_table': 'assignments',
            },
        ),
    ]
