# Generated by Django 3.1.2 on 2020-12-02 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user3',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user4',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user5',
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_description',
            field=models.CharField(max_length=100),
        ),
    ]
