# Generated by Django 3.1.2 on 2020-12-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0002_auto_20201201_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='classes',
        ),
        migrations.AddField(
            model_name='group',
            name='classes',
            field=models.ManyToManyField(to='loginpage.Classes'),
        ),
    ]
