# Generated by Django 3.1.2 on 2020-12-04 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0002_auto_20201202_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='group_id',
            new_name='group',
        ),
    ]
