# Generated by Django 3.1.2 on 2020-12-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0002_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_name',
            field=models.CharField(default='No_Name', max_length=20),
        ),
    ]
