# Generated by Django 3.1.2 on 2020-12-01 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0003_classes_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='class_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='loginpage.classes'),
            preserve_default=False,
        ),
    ]
