# Generated by Django 3.1.2 on 2020-12-01 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0004_assignment_class_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assignment',
            table='assignments',
        ),
    ]
