# Generated by Django 3.1.2 on 2020-12-01 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0005_auto_20201201_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='classes',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='loginpage.classes'),
        ),
    ]
