# Generated by Django 3.1.2 on 2020-12-02 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginpage', '0006_auto_20201201_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='classes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='loginpage.classes'),
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
